baseURL: http://example.org/
languageCode: en-us
title: First steps with Hugo
theme: hugo-theme-techdoc
ignoreFiles:
  # we'll have to ignore the files that are embedded in the notebooks
  - df.html
  - dt.html
  - dt2.html
  - widget_example.html
# This avoids an error about a missing index.json
outputs:
  home:
    - HTML
    - JSON
# Params for the hugo-theme-techdoc theme
params:
  # Source Code repository section
  description: What kind of content will work in Hugo?
  # Project repository
  github_repository: https://github.com/mwouts/first_steps_with_hugo
  # Documentation repository
  github_doc_repository: https://github.com/mwouts/first_steps_with_hugo

  # Documentation Menu section
  # Menu style settings: "open-menu" or "slide-menu"
  menu_style: "open-menu"

  # Date format
  # default "2 Jan 2006"
  dateformat: ""
  # See the format reference https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference

  # path name excluded from documentation menu
  menu_exclusion: [
      "archives",
      "archive",
      "blog",
      "entry",
      "post",
      "posts"
  ]

# Global menu section menu:
menu:
  main:
    - name: Home
      url: "/"
      weight: 1
    - name: Twitter
      url: "https://twitter.com/marcwouts"
      weight: 2